Add a build.sh Script for compilation
Adding abuild.sh script and removing all the build instructions from the
workflow. This makes handling the build instructions efficiently without
getting to alter the workflows.

Signed-off-by: Hasibur Rahman Mohammed <hasiburr@qti.qualcomm.com>

diff --git a/.github/actions/build/action.yml b/.github/actions/build/action.yml
--- a/.github/actions/build/action.yml
+++ b/.github/actions/build/action.yml
@@ -10,54 +10,34 @@ inputs:
 runs:
   using: 'composite'
   steps:
-    - name: Clone meta-ar
-      shell: bash
-      run: |
-        # Clone the meta-ar repository
-        cd ${{ github.workspace }}/..
-        # Check if the directory already exists
-        if [ -d "meta-ar" ]; then
-          echo "Directory meta-ar already exists. Pulling latest changes."
-          cd meta-ar
-          git reset --hard origin/main
-          git pull origin main
-        else
-          echo "Directory meta-ar does not exist. Cloning repository."
-          git clone https://github.com/Audioreach/meta-ar.git
-        fi
-
     - name: Build Project
       id: build
       shell: bash
       run: |
         # Load the build arguments
         set +x
-
-        # Apply patch
-        git apply ../meta-ar/recipes/audio/audioreach-graphservices/0001-ar_osal-update-msm_audio.h-header-include-path.patch
+        export GITHUB_WORKSPACE="${{ github.workspace }}"
+        export CONFIG_SCRIPT="${{ env.CONFIG_SCRIPT }}"
+        source ./${{ env.SYNC_SCRIPT }}
+        source ./${{ env.APPLY_PATCH_SCRIPT }}
 
         # Build inside a docker container
         docker run \
           --rm \
           --user $(id -u):$(id -g) \
-          -v $PWD:$PWD \
+          -v $PWD/..:$PWD/.. \
           -w $PWD \
-          -e "GITHUB_WORKSPACE=${{ github.workspace }}" \
-          -e "BUILD_ARGS=${{ env.BUILD_ARGS }}" \
-          -e "KERNEL_VERSION=${{ env.KERNEL_VERSION }}" \
+          -e GITHUB_WORKSPACE="${{ github.workspace }}" \
+          -e BUILD_ARGS="${{ env.BUILD_ARGS }}" \
+          -e KERNEL_VERSION="${{ env.KERNEL_VERSION }}" \
+          -e BUILD_SCRIPT="${{ env.BUILD_SCRIPT }}" \
           --privileged \
           ${{ inputs.docker_image }} \
-          bash -c "
-            set +x
-            source ./install/environment-setup-armv8-2a-poky-linux
-            autoreconf -Wcross --verbose --install --force --exclude=autopoint
-            autoconf --force
-
-            # Run the configure script with the specified arguments
-            ./configure CFLAGS=\"-Wno-int-conversion\" \${BUILD_ARGS} --with-sanitized-headers=\${GITHUB_WORKSPACE}/install/sysroots/armv8-2a-poky-linux/usr/lib/modules/\$KERNEL_VERSION/build/include/uapi/sound/qcom
-            # make
-            make DESTDIR=\${GITHUB_WORKSPACE}/build install
-            "
+          bash -c '
+            echo "Running build script... : ${BUILD_SCRIPT}"
+            ls -l "${BUILD_SCRIPT}" || (echo "Build script not found!" && exit 1)
+            source ./${BUILD_SCRIPT}
+            '
 
     - name: Create build.tar
       id: create_build_tar
